/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRoutesRouteRouteImport } from './routes/_authenticated-routes/route'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesPastplayedRouteImport } from './routes/games/pastplayed'
import { Route as AuthenticatedRoutesPlayPersonRouteImport } from './routes/_authenticated-routes/play-person'
import { Route as AuthenticatedRoutesPlayComputerRouteImport } from './routes/_authenticated-routes/play-computer'
import { Route as AuthenticatedRoutesDashboardRouteImport } from './routes/_authenticated-routes/dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoutesRouteRoute =
  AuthenticatedRoutesRouteRouteImport.update({
    id: '/_authenticated-routes',
    getParentRoute: () => rootRouteImport,
  } as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPastplayedRoute = GamesPastplayedRouteImport.update({
  id: '/games/pastplayed',
  path: '/games/pastplayed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoutesPlayPersonRoute =
  AuthenticatedRoutesPlayPersonRouteImport.update({
    id: '/play-person',
    path: '/play-person',
    getParentRoute: () => AuthenticatedRoutesRouteRoute,
  } as any)
const AuthenticatedRoutesPlayComputerRoute =
  AuthenticatedRoutesPlayComputerRouteImport.update({
    id: '/play-computer',
    path: '/play-computer',
    getParentRoute: () => AuthenticatedRoutesRouteRoute,
  } as any)
const AuthenticatedRoutesDashboardRoute =
  AuthenticatedRoutesDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoutesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedRoutesDashboardRoute
  '/play-computer': typeof AuthenticatedRoutesPlayComputerRoute
  '/play-person': typeof AuthenticatedRoutesPlayPersonRoute
  '/games/pastplayed': typeof GamesPastplayedRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedRoutesDashboardRoute
  '/play-computer': typeof AuthenticatedRoutesPlayComputerRoute
  '/play-person': typeof AuthenticatedRoutesPlayPersonRoute
  '/games/pastplayed': typeof GamesPastplayedRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated-routes': typeof AuthenticatedRoutesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated-routes/dashboard': typeof AuthenticatedRoutesDashboardRoute
  '/_authenticated-routes/play-computer': typeof AuthenticatedRoutesPlayComputerRoute
  '/_authenticated-routes/play-person': typeof AuthenticatedRoutesPlayPersonRoute
  '/games/pastplayed': typeof GamesPastplayedRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/play-computer'
    | '/play-person'
    | '/games/pastplayed'
    | '/games'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/play-computer'
    | '/play-person'
    | '/games/pastplayed'
    | '/games'
  id:
    | '__root__'
    | '/_authenticated-routes'
    | '/about'
    | '/login'
    | '/signup'
    | '/_authenticated-routes/dashboard'
    | '/_authenticated-routes/play-computer'
    | '/_authenticated-routes/play-person'
    | '/games/pastplayed'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoutesRouteRoute: typeof AuthenticatedRoutesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  GamesPastplayedRoute: typeof GamesPastplayedRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated-routes': {
      id: '/_authenticated-routes'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/pastplayed': {
      id: '/games/pastplayed'
      path: '/games/pastplayed'
      fullPath: '/games/pastplayed'
      preLoaderRoute: typeof GamesPastplayedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated-routes/play-person': {
      id: '/_authenticated-routes/play-person'
      path: '/play-person'
      fullPath: '/play-person'
      preLoaderRoute: typeof AuthenticatedRoutesPlayPersonRouteImport
      parentRoute: typeof AuthenticatedRoutesRouteRoute
    }
    '/_authenticated-routes/play-computer': {
      id: '/_authenticated-routes/play-computer'
      path: '/play-computer'
      fullPath: '/play-computer'
      preLoaderRoute: typeof AuthenticatedRoutesPlayComputerRouteImport
      parentRoute: typeof AuthenticatedRoutesRouteRoute
    }
    '/_authenticated-routes/dashboard': {
      id: '/_authenticated-routes/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedRoutesDashboardRouteImport
      parentRoute: typeof AuthenticatedRoutesRouteRoute
    }
  }
}

interface AuthenticatedRoutesRouteRouteChildren {
  AuthenticatedRoutesDashboardRoute: typeof AuthenticatedRoutesDashboardRoute
  AuthenticatedRoutesPlayComputerRoute: typeof AuthenticatedRoutesPlayComputerRoute
  AuthenticatedRoutesPlayPersonRoute: typeof AuthenticatedRoutesPlayPersonRoute
}

const AuthenticatedRoutesRouteRouteChildren: AuthenticatedRoutesRouteRouteChildren =
  {
    AuthenticatedRoutesDashboardRoute: AuthenticatedRoutesDashboardRoute,
    AuthenticatedRoutesPlayComputerRoute: AuthenticatedRoutesPlayComputerRoute,
    AuthenticatedRoutesPlayPersonRoute: AuthenticatedRoutesPlayPersonRoute,
  }

const AuthenticatedRoutesRouteRouteWithChildren =
  AuthenticatedRoutesRouteRoute._addFileChildren(
    AuthenticatedRoutesRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoutesRouteRoute: AuthenticatedRoutesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  GamesPastplayedRoute: GamesPastplayedRoute,
  GamesIndexRoute: GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
