/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as NonAuthenticatedRoutesRouteRouteImport } from './routes/_non-authenticated-routes/route'
import { Route as AuthenticatedRoutesRouteRouteImport } from './routes/_authenticated-routes/route'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as NonAuthenticatedRoutesIndexRouteImport } from './routes/_non-authenticated-routes/index'
import { Route as GamesPastplayedRouteImport } from './routes/games/pastplayed'
import { Route as NonAuthenticatedRoutesSignupRouteImport } from './routes/_non-authenticated-routes/signup'
import { Route as NonAuthenticatedRoutesLoginRouteImport } from './routes/_non-authenticated-routes/login'
import { Route as NonAuthenticatedRoutesForgotPasswordRouteImport } from './routes/_non-authenticated-routes/forgot-password'
import { Route as AuthenticatedRoutesPlayPersonRouteImport } from './routes/_authenticated-routes/play-person'
import { Route as AuthenticatedRoutesPlayComputerRouteImport } from './routes/_authenticated-routes/play-computer'
import { Route as AuthenticatedRoutesDashboardRouteImport } from './routes/_authenticated-routes/dashboard'
import { Route as NonAuthenticatedRoutesResetPasswordIndexRouteImport } from './routes/_non-authenticated-routes/reset-password/index'
import { Route as NonAuthenticatedRoutesResetPasswordTokenRouteImport } from './routes/_non-authenticated-routes/reset-password/$token'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const NonAuthenticatedRoutesRouteRoute =
  NonAuthenticatedRoutesRouteRouteImport.update({
    id: '/_non-authenticated-routes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRoutesRouteRoute =
  AuthenticatedRoutesRouteRouteImport.update({
    id: '/_authenticated-routes',
    getParentRoute: () => rootRouteImport,
  } as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const NonAuthenticatedRoutesIndexRoute =
  NonAuthenticatedRoutesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NonAuthenticatedRoutesRouteRoute,
  } as any)
const GamesPastplayedRoute = GamesPastplayedRouteImport.update({
  id: '/games/pastplayed',
  path: '/games/pastplayed',
  getParentRoute: () => rootRouteImport,
} as any)
const NonAuthenticatedRoutesSignupRoute =
  NonAuthenticatedRoutesSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => NonAuthenticatedRoutesRouteRoute,
  } as any)
const NonAuthenticatedRoutesLoginRoute =
  NonAuthenticatedRoutesLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => NonAuthenticatedRoutesRouteRoute,
  } as any)
const NonAuthenticatedRoutesForgotPasswordRoute =
  NonAuthenticatedRoutesForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => NonAuthenticatedRoutesRouteRoute,
  } as any)
const AuthenticatedRoutesPlayPersonRoute =
  AuthenticatedRoutesPlayPersonRouteImport.update({
    id: '/play-person',
    path: '/play-person',
    getParentRoute: () => AuthenticatedRoutesRouteRoute,
  } as any)
const AuthenticatedRoutesPlayComputerRoute =
  AuthenticatedRoutesPlayComputerRouteImport.update({
    id: '/play-computer',
    path: '/play-computer',
    getParentRoute: () => AuthenticatedRoutesRouteRoute,
  } as any)
const AuthenticatedRoutesDashboardRoute =
  AuthenticatedRoutesDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoutesRouteRoute,
  } as any)
const NonAuthenticatedRoutesResetPasswordIndexRoute =
  NonAuthenticatedRoutesResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => NonAuthenticatedRoutesRouteRoute,
  } as any)
const NonAuthenticatedRoutesResetPasswordTokenRoute =
  NonAuthenticatedRoutesResetPasswordTokenRouteImport.update({
    id: '/reset-password/$token',
    path: '/reset-password/$token',
    getParentRoute: () => NonAuthenticatedRoutesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/dashboard': typeof AuthenticatedRoutesDashboardRoute
  '/play-computer': typeof AuthenticatedRoutesPlayComputerRoute
  '/play-person': typeof AuthenticatedRoutesPlayPersonRoute
  '/forgot-password': typeof NonAuthenticatedRoutesForgotPasswordRoute
  '/login': typeof NonAuthenticatedRoutesLoginRoute
  '/signup': typeof NonAuthenticatedRoutesSignupRoute
  '/games/pastplayed': typeof GamesPastplayedRoute
  '/': typeof NonAuthenticatedRoutesIndexRoute
  '/games': typeof GamesIndexRoute
  '/reset-password/$token': typeof NonAuthenticatedRoutesResetPasswordTokenRoute
  '/reset-password': typeof NonAuthenticatedRoutesResetPasswordIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/dashboard': typeof AuthenticatedRoutesDashboardRoute
  '/play-computer': typeof AuthenticatedRoutesPlayComputerRoute
  '/play-person': typeof AuthenticatedRoutesPlayPersonRoute
  '/forgot-password': typeof NonAuthenticatedRoutesForgotPasswordRoute
  '/login': typeof NonAuthenticatedRoutesLoginRoute
  '/signup': typeof NonAuthenticatedRoutesSignupRoute
  '/games/pastplayed': typeof GamesPastplayedRoute
  '/': typeof NonAuthenticatedRoutesIndexRoute
  '/games': typeof GamesIndexRoute
  '/reset-password/$token': typeof NonAuthenticatedRoutesResetPasswordTokenRoute
  '/reset-password': typeof NonAuthenticatedRoutesResetPasswordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated-routes': typeof AuthenticatedRoutesRouteRouteWithChildren
  '/_non-authenticated-routes': typeof NonAuthenticatedRoutesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_authenticated-routes/dashboard': typeof AuthenticatedRoutesDashboardRoute
  '/_authenticated-routes/play-computer': typeof AuthenticatedRoutesPlayComputerRoute
  '/_authenticated-routes/play-person': typeof AuthenticatedRoutesPlayPersonRoute
  '/_non-authenticated-routes/forgot-password': typeof NonAuthenticatedRoutesForgotPasswordRoute
  '/_non-authenticated-routes/login': typeof NonAuthenticatedRoutesLoginRoute
  '/_non-authenticated-routes/signup': typeof NonAuthenticatedRoutesSignupRoute
  '/games/pastplayed': typeof GamesPastplayedRoute
  '/_non-authenticated-routes/': typeof NonAuthenticatedRoutesIndexRoute
  '/games/': typeof GamesIndexRoute
  '/_non-authenticated-routes/reset-password/$token': typeof NonAuthenticatedRoutesResetPasswordTokenRoute
  '/_non-authenticated-routes/reset-password/': typeof NonAuthenticatedRoutesResetPasswordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/dashboard'
    | '/play-computer'
    | '/play-person'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/games/pastplayed'
    | '/'
    | '/games'
    | '/reset-password/$token'
    | '/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/dashboard'
    | '/play-computer'
    | '/play-person'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/games/pastplayed'
    | '/'
    | '/games'
    | '/reset-password/$token'
    | '/reset-password'
  id:
    | '__root__'
    | '/_authenticated-routes'
    | '/_non-authenticated-routes'
    | '/about'
    | '/_authenticated-routes/dashboard'
    | '/_authenticated-routes/play-computer'
    | '/_authenticated-routes/play-person'
    | '/_non-authenticated-routes/forgot-password'
    | '/_non-authenticated-routes/login'
    | '/_non-authenticated-routes/signup'
    | '/games/pastplayed'
    | '/_non-authenticated-routes/'
    | '/games/'
    | '/_non-authenticated-routes/reset-password/$token'
    | '/_non-authenticated-routes/reset-password/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoutesRouteRoute: typeof AuthenticatedRoutesRouteRouteWithChildren
  NonAuthenticatedRoutesRouteRoute: typeof NonAuthenticatedRoutesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  GamesPastplayedRoute: typeof GamesPastplayedRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_non-authenticated-routes': {
      id: '/_non-authenticated-routes'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NonAuthenticatedRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated-routes': {
      id: '/_authenticated-routes'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_non-authenticated-routes/': {
      id: '/_non-authenticated-routes/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NonAuthenticatedRoutesIndexRouteImport
      parentRoute: typeof NonAuthenticatedRoutesRouteRoute
    }
    '/games/pastplayed': {
      id: '/games/pastplayed'
      path: '/games/pastplayed'
      fullPath: '/games/pastplayed'
      preLoaderRoute: typeof GamesPastplayedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_non-authenticated-routes/signup': {
      id: '/_non-authenticated-routes/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof NonAuthenticatedRoutesSignupRouteImport
      parentRoute: typeof NonAuthenticatedRoutesRouteRoute
    }
    '/_non-authenticated-routes/login': {
      id: '/_non-authenticated-routes/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof NonAuthenticatedRoutesLoginRouteImport
      parentRoute: typeof NonAuthenticatedRoutesRouteRoute
    }
    '/_non-authenticated-routes/forgot-password': {
      id: '/_non-authenticated-routes/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof NonAuthenticatedRoutesForgotPasswordRouteImport
      parentRoute: typeof NonAuthenticatedRoutesRouteRoute
    }
    '/_authenticated-routes/play-person': {
      id: '/_authenticated-routes/play-person'
      path: '/play-person'
      fullPath: '/play-person'
      preLoaderRoute: typeof AuthenticatedRoutesPlayPersonRouteImport
      parentRoute: typeof AuthenticatedRoutesRouteRoute
    }
    '/_authenticated-routes/play-computer': {
      id: '/_authenticated-routes/play-computer'
      path: '/play-computer'
      fullPath: '/play-computer'
      preLoaderRoute: typeof AuthenticatedRoutesPlayComputerRouteImport
      parentRoute: typeof AuthenticatedRoutesRouteRoute
    }
    '/_authenticated-routes/dashboard': {
      id: '/_authenticated-routes/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedRoutesDashboardRouteImport
      parentRoute: typeof AuthenticatedRoutesRouteRoute
    }
    '/_non-authenticated-routes/reset-password/': {
      id: '/_non-authenticated-routes/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof NonAuthenticatedRoutesResetPasswordIndexRouteImport
      parentRoute: typeof NonAuthenticatedRoutesRouteRoute
    }
    '/_non-authenticated-routes/reset-password/$token': {
      id: '/_non-authenticated-routes/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof NonAuthenticatedRoutesResetPasswordTokenRouteImport
      parentRoute: typeof NonAuthenticatedRoutesRouteRoute
    }
  }
}

interface AuthenticatedRoutesRouteRouteChildren {
  AuthenticatedRoutesDashboardRoute: typeof AuthenticatedRoutesDashboardRoute
  AuthenticatedRoutesPlayComputerRoute: typeof AuthenticatedRoutesPlayComputerRoute
  AuthenticatedRoutesPlayPersonRoute: typeof AuthenticatedRoutesPlayPersonRoute
}

const AuthenticatedRoutesRouteRouteChildren: AuthenticatedRoutesRouteRouteChildren =
  {
    AuthenticatedRoutesDashboardRoute: AuthenticatedRoutesDashboardRoute,
    AuthenticatedRoutesPlayComputerRoute: AuthenticatedRoutesPlayComputerRoute,
    AuthenticatedRoutesPlayPersonRoute: AuthenticatedRoutesPlayPersonRoute,
  }

const AuthenticatedRoutesRouteRouteWithChildren =
  AuthenticatedRoutesRouteRoute._addFileChildren(
    AuthenticatedRoutesRouteRouteChildren,
  )

interface NonAuthenticatedRoutesRouteRouteChildren {
  NonAuthenticatedRoutesForgotPasswordRoute: typeof NonAuthenticatedRoutesForgotPasswordRoute
  NonAuthenticatedRoutesLoginRoute: typeof NonAuthenticatedRoutesLoginRoute
  NonAuthenticatedRoutesSignupRoute: typeof NonAuthenticatedRoutesSignupRoute
  NonAuthenticatedRoutesIndexRoute: typeof NonAuthenticatedRoutesIndexRoute
  NonAuthenticatedRoutesResetPasswordTokenRoute: typeof NonAuthenticatedRoutesResetPasswordTokenRoute
  NonAuthenticatedRoutesResetPasswordIndexRoute: typeof NonAuthenticatedRoutesResetPasswordIndexRoute
}

const NonAuthenticatedRoutesRouteRouteChildren: NonAuthenticatedRoutesRouteRouteChildren =
  {
    NonAuthenticatedRoutesForgotPasswordRoute:
      NonAuthenticatedRoutesForgotPasswordRoute,
    NonAuthenticatedRoutesLoginRoute: NonAuthenticatedRoutesLoginRoute,
    NonAuthenticatedRoutesSignupRoute: NonAuthenticatedRoutesSignupRoute,
    NonAuthenticatedRoutesIndexRoute: NonAuthenticatedRoutesIndexRoute,
    NonAuthenticatedRoutesResetPasswordTokenRoute:
      NonAuthenticatedRoutesResetPasswordTokenRoute,
    NonAuthenticatedRoutesResetPasswordIndexRoute:
      NonAuthenticatedRoutesResetPasswordIndexRoute,
  }

const NonAuthenticatedRoutesRouteRouteWithChildren =
  NonAuthenticatedRoutesRouteRoute._addFileChildren(
    NonAuthenticatedRoutesRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoutesRouteRoute: AuthenticatedRoutesRouteRouteWithChildren,
  NonAuthenticatedRoutesRouteRoute:
    NonAuthenticatedRoutesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  GamesPastplayedRoute: GamesPastplayedRoute,
  GamesIndexRoute: GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
